name: Docker Tests

on: [push]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Docker Network
        run: docker network create mynetwork

      - name: Build Gleaner Docker Image
        run: docker build -t gleaner .

      - name: Run Minio Container
        run: |
          docker run -d --rm --network mynetwork --name minio minio/minio server /data

      - name: Wait for Minio to be Ready
        run: |
          end=$(date -ud '+30 seconds' +%s)
          while ! nc -z minio 9000; do
            sleep 1
            now=$(date -u +%s)
            if [ $now -gt $end ]; then
              echo "Timeout waiting for Minio"
              exit 1
            fi
          done

      - name: Run Gleaner
        run: |
          docker run --network mynetwork \
            -v ./testHelpers/sampleConfigs/justHu02.yaml:/app/gleanerconfig.yaml \
            --rm gleaner --cfg gleanerconfig.yaml --setup --address minio
