name: Docker Tests

on: [push]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
     
      - name: Build Docker Image
        run: docker build -t gleaner .

      - name: Run Minio Container
        run: |
            docker run -d --rm -p 9000:9000 minio/minio server /data


      - name: Wait for minio to be ready
        run: |
          end=$(date -ud '+30 seconds' +%s)
          while ! nc -z 127.0.0.1 9000; do
            sleep 1
            now=$(date -u +%s)
            if [ $now -gt $end ]; then
              echo "Timeout waiting for minio"
              exit 1
            fi
          done

      - name: Run Gleaner
        run: docker run -v ./testHelpers/sampleConfigs/justHu02.yaml:/app/gleanerconfig.yaml --rm gleaner --cfg gleanerconfig.yaml --setup

