name: Test Gleaner against pids.geoconnex.dev Sitemap

on:
  [ pull_request, workflow_dispatch ]
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.20'
      - run: go version
