name: Build and Push to Docker Hub

on:
  push:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build but don't push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
