name: Test Gleaner against pids.geoconnex.dev Sitemap

on:
  [  workflow_dispatch ]
jobs:
  main:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.20'
      - run: sudo apt-get install make
      - run: sudo apt-get install git 
      - run: mkdir -p $HOME/bin
      - run: curl https://dl.min.io/client/mc/release/linux-amd64/mc -o $HOME/bin/mc && chmod +x $HOME/bin/mc 
      - run: sh scripts/iow/start-headless-chrome.sh
      - run: sh scripts/iow/start-minio.sh && sleep 3
      - run: $HOME/bin/mc alias set myminio http://localhost:9000 amazingaccesskey amazingsecretkey
      - run: mc mb myminio/iow
      - run: make 
      - run: sh scripts/iow/start-gleaner.sh      
